"""
Optimize representative molecular structures and perform vibrational analysis.

This script processes molecular medoid structures stored in the ``medoids``
directory. Each structure is geometry-optimized using a FAIRChem machine
learning interatomic potential and subsequently subjected to a vibrational
frequency analysis.

For each molecular structure, the script:

1. Reads the medoid geometry from an XYZ file.
2. Assigns a FAIRChem calculator based on the specified pretrained model.
3. Optimizes the molecular geometry using the BFGS optimizer.
4. Performs a vibrational frequency calculation on the optimized geometry.
5. Identifies imaginary vibrational frequencies.
6. Determines a SMILES representation of the optimized structure.
7. Stores the calculated information in a dictionary.
8. Writes the optimized geometry to the ``opts`` directory.
9. Serializes the complete analysis dictionary to ``analysis.pkl``.

SMILES generation is first attempted using RDKit's connectivity and bond-order
determination routines. If RDKit cannot determine a chemically valid bonding
pattern, a fallback procedure constructs molecular connectivity from an ASE
neighbor list and represents all detected bonds as single bonds.

Input
-----
medoids/
    Directory containing representative molecular structures in XYZ format.

Model
-----
The FAIRChem prediction model is loaded from the path specified by ``dataset``
and used through ``FAIRChemCalculator`` for geometry optimization and
vibrational calculations.

Output
------
opts/
    Directory containing the optimized molecular geometries in XYZ format.

analysis.pkl
    Pickled dictionary containing, for each molecular formula, the SMILES
    representation of the optimized structure, the indices of imaginary
    frequencies, and their corresponding imaginary components.

Notes
-----
The script assumes that the required FAIRChem model is available at the
specified path and that the input structures are compatible with the selected
calculator.

The fallback SMILES construction is based on geometric neighbor detection
rather than explicit bond-order determination. SMILES generated by this
fallback route are therefore marked by appending ``"NeighborList"``.
"""

import numpy as np
import os
from ase.io import read
from ase.neighborlist import NeighborList, natural_cutoffs
from ase.neighborlist import neighbor_list
from rdkit import Chem
from rdkit.Chem import rdDetermineBonds
from collections import Counter
from rdkit.Geometry import Point3D
from ase.io import write
import pickle
from fairchem.core.units.mlip_unit import load_predict_unit
from fairchem.core import FAIRChemCalculator
from ase.optimize import BFGS
from ase.vibrations import Vibrations



def get_smiles(molecule) :
    """
    Generate a SMILES representation of an ASE molecular structure.

    The function first attempts to determine molecular connectivity and bond
    orders using RDKit. The Cartesian coordinates and atomic symbols from the
    ASE ``Atoms`` object are transferred to an RDKit molecule, after which
    ``DetermineConnectivity`` and ``DetermineBondOrders`` are used to infer
    the molecular bonding pattern.

    If RDKit's bond-order determination raises a ``ValueError``, the function
    falls back to connectivity inferred from an ASE ``NeighborList``. In this
    fallback procedure, neighboring atoms are connected using single bonds.
    Hydrogen and carbon cutoff radii are slightly increased before constructing
    the neighbor list. SMILES strings produced by this fallback route are
    marked by appending ``"NeighborList"``.

    Parameters
    ----------
    molecule : ase.Atoms
        Molecular structure containing atomic symbols and Cartesian
        coordinates.

    Returns
    -------
    str
        SMILES representation of the molecular structure. If the fallback
        neighbor-list procedure is used, ``"NeighborList"`` is appended to
        the generated SMILES string.

    Notes
    -----
    The RDKit bond-determination procedure assumes a total molecular charge
    of zero.

    The neighbor-list fallback determines connectivity geometrically and
    assigns every detected bond as a single bond. Consequently, the resulting
    SMILES may not contain chemically correct bond orders.
    """

    # Initialize the molecular formula and assume that RDKit connectivity
    # and bond-order determination will succeed.
    symbol = molecule.get_chemical_formula()
    status = True


    if status :
        # Create an RDKit conformer containing the Cartesian coordinates
        # of all atoms in the ASE molecular structure.
        #fragments.append(molecule)
        conf = Chem.Conformer(len(molecule))

        # Construct an editable RDKit molecule and transfer each atom,
        # including its element and Cartesian position.
        rw = Chem.RWMol()
        for i, atom in enumerate(molecule) :
            position = atom.position
            conf.SetAtomPosition(i, Point3D(position[0], position[1], position[2]))
            rw.AddAtom(Chem.Atom(atom.symbol))

        # Convert the editable molecule to a regular RDKit molecule and
        # attach the conformer containing the molecular geometry.
        mol = rw.GetMol()
        mol.AddConformer(conf, assignId=True)
        symbol = molecule.get_chemical_formula()

        # Assume a neutral total molecular charge during RDKit bond
        # determination.
        charge = 0

        try :
            # Work on a copy of the RDKit molecule before determining
            # connectivity and assigning bond orders.
            conn_mol = Chem.Mol(mol)
            rdDetermineBonds.DetermineConnectivity(conn_mol, charge=charge) # covFactor=1.6,

            rdDetermineBonds.DetermineBondOrders(conn_mol, allowChargedFragments=True, charge=charge, embedChiral=False, maxIterations=500)

            # Convert the resulting molecular graph to a SMILES string.
            smiles = Chem.MolToSmiles(conn_mol)
    
        except ValueError:
            # If RDKit cannot determine a valid bonding pattern, trigger
            # the neighbor-list-based fallback procedure below.
            status = False

    if not status :
        # Construct an editable RDKit molecule for the fallback connectivity
        # determination.
        rw = Chem.RWMol()
        chemical_symbols = molecule.get_chemical_symbols()

        # Generate element-dependent natural cutoff radii for neighbor
        # detection. The H and C cutoffs are increased slightly to make
        # connectivity detection more permissive for these elements.
        skin = 0.1
        cutoffs = natural_cutoffs(molecule, mult=1.0)
        for i, atom in enumerate(molecule)  :
            if atom.symbol == "H" :
                cutoffs[i] *= 1.4
            if atom.symbol == "C" :
                cutoffs[i] *= 1.1

        # Build and update the ASE neighbor list for the current geometry.
        nl_fragment = NeighborList(cutoffs=cutoffs, self_interaction=False, bothways=False, skin=skin)
        nl_fragment.update(molecule)

        # Extract atom pairs identified as bonded by the neighbor list.
        bonds = []
        for atom in range(len(molecule)) :
            indices, offsets = nl_fragment.get_neighbors(atom)
            
            for index in indices :
                bonds.append((atom, index))
        
        # Add all atoms to the fallback RDKit molecular graph.
        for atom in chemical_symbols :
            rw.AddAtom(Chem.Atom(atom))

        # Represent every connection detected by the neighbor list as
        # a single bond.
        for i, j in bonds :
            rw.AddBond(int(i), int(j), Chem.BondType.SINGLE)

        # Generate the fallback SMILES and mark it explicitly so that these
        # results can be distinguished from RDKit bond-order assignments.
        mol = Chem.Mol(rw)
        smiles = Chem.MolToSmiles(mol) + "NeighborList"


    return smiles



# %%
# Path to the pretrained FAIRChem model used for energy and force prediction.
dataset = "/u/tcc/lina4889/DEPOSITORY/datasets/esen_sm_conserving_all.pt"


# Load the FAIRChem prediction unit and construct an ASE-compatible calculator.
predictor = load_predict_unit(dataset)
calc = FAIRChemCalculator(predictor, task_name="omol")

# Dictionary used to collect the analysis results for each molecular structure.
analysis = {}

# Create the directory for optimized structures if it does not already exist.
if not os.path.isdir("opts") :
    os.mkdir("opts") 

# Process each representative molecular structure stored in the medoids
# directory.
for dataset in os.listdir("medoids") :
    
    # Obtain the molecular identifier from the filename and read its geometry.
    formula = dataset[:-4]
    medoid =  read(f"medoids/{dataset}")
    
    
    # Skip the explicitly identified H2 neighbor-list structure.
    if formula != "[HH]NeighborList" :
        
        print(f" {formula} ".center(60, "#"))
        
        # Assign the FAIRChem calculator and optimize the molecular geometry
        # using BFGS until the requested maximum-force threshold is reached.
        mol = medoid
        mol.calc = calc
        BFGS(mol).run(fmax=0.001)


        # Frequency analysis
        # Calculate vibrational modes and frequencies for the optimized
        # molecular structure.
        vib = Vibrations(mol)
        vib.run()

        # Identify modes with nonzero positive imaginary components and
        # retain both their indices and imaginary-frequency values.
        n_imag_freqs_ids = [i for i, y in enumerate(vib.get_frequencies().imag) if y > 0]
        n_imag_freqs_values = [y for y in vib.get_frequencies().imag if y > 0]

        # Determine the molecular connectivity/SMILES after optimization.
        new_smiles = get_smiles(mol)

        # Print the standard ASE vibrational summary.
        vib.summary()
        vib.clean()
        
        # Report and store the molecular identifier, optimized connectivity,
        # and information about imaginary vibrational modes.
        print(formula, new_smiles, n_imag_freqs_ids, n_imag_freqs_values)
        analysis[formula] = [new_smiles, n_imag_freqs_ids, n_imag_freqs_values]
        print("-"*60)

        
        # Save the optimized molecular geometry as an XYZ file.
        write(f"opts/{formula}.xyz", mol)
 
# Serialize the collected analysis results for later processing.
with open("analysis.pkl", "wb") as f:
    pickle.dump(analysis, f)

